### ISSUE TITLE
Uplate site provides out-of-date jar versions

### ISSUE THREAD

**Issue by ssgpers** [tischi/fly-reg#10]
@tischi 

Update site provides 0.1.0 version of the FlyReg.

Feedback microscopy pipelines are compiled with 0.1.3-SNAPSHOT and do not work with 0.1.0

Would be great to release stable 0.1.3 and also make it available via update site.

Please also check the version of imagej-utils there, right now I get via update site 0.5.7-SNAPSHOT

**Comment by tischi** [comment]
Should be done.

You can also [find it now on maven](https://maven.scijava.org/#nexus-search;quick~fly-reg).

```
<dependency>
  <groupId>de.embl.cba</groupId>
  <artifactId>fly-reg</artifactId>
  <version>0.1.3</version>
</dependency>
```

**Comment by tischi** [comment]
If you use it via maven better use:

```
<dependency>
  <groupId>de.embl.cba</groupId>
  <artifactId>fly-reg</artifactId>
  <version>0.1.4</version>
</dependency>
```

I am not sure the `0.1.3` was really uploaded properly to maven.

**Comment by ssgpers** [comment]
FYI: update site still provides 0.1.3

**Comment by tischi** [comment]
I know, but that should be identical to 0.1.4
