### ISSUE TITLE
Class msiing

### ISSUE THREAD

**Issue by ssgpers** [tischi/fly-reg#8]
@tischi 

Class which we used in drosophila screen project does not exist anymore:

![image](https://user-images.githubusercontent.com/6419504/115522791-b58d7580-a28c-11eb-849c-9417c5fb7527.png)

Do I need to update the code or will you reintroduce this class?

**Comment by tischi** [comment]
It looks like it has been renamed to `FlyEmbryoNerveCordRegistration`:

<img width="337" alt="image" src="https://user-images.githubusercontent.com/2157566/115524071-05207100-a28e-11eb-9f83-a32c905b6ee3.png">

**Comment by ssgpers** [comment]
I exchanged the class name, now it complains that class needs to be parametrised.

![image](https://user-images.githubusercontent.com/6419504/115536437-153e4d80-a29a-11eb-9897-504df136cc01.png)

Before it was somehow working, just giving warning, now I have an error:

You can clone embryo screen project and test. These are my classes affected:
https://git.embl.de/grp-almf/feedback-fly-embryo-crocker/-/blob/master/src/main/java/feedback/fly/embryo/jobs/Job_FocusEmbryoAutoDatasetSplit.java
https://git.embl.de/grp-almf/feedback-fly-embryo-crocker/-/blob/master/src/test/java/algorithm/tests/FindEmbryoOrientationTischi.java

**Comment by tischi** [comment]
You have declare the type indeed. You could declare it at the level of the calling class or function.
For example:

```
public static < T extends RealType< T > & NativeType< T > > void register()
{
	final FlyEmbryoNerveCordRegistration< T > registration = new FlyEmbryoNerveCordRegistration<>( settings, opService );

	registration.run( ... );
}
```

Probably there is another way of doing this on my side, but that should be the quickest solution.

**Comment by ssgpers** [comment]
Works now, thanks. Needed to make the method static in order not to parametrize entire class.
